package com.matteodri.owlenergymonitor.services;


import java.net.InetAddress;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.stereotype.Service;

/**
 * Service processing messages generated by the Owl Network.
 *
 * @author Matteo Dri 05 Nov 2019
 */

@Service
public class OwlMessageProcessor {
    private static final Logger logger = LogManager.getLogger(OwlMessageProcessor.class);

    public OwlMessageProcessor() {
    }

    public void process(InetAddress fromAddress, String message){
        logger.debug("Message received from {}: {}", fromAddress, message);
    }

}
