package com.matteodri.owlenergymonitor.services;


import java.net.InetAddress;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.matteodri.owlenergymonitor.model.electricity.Electricity;
import com.matteodri.owlenergymonitor.model.solar.Solar;
import com.matteodri.owlenergymonitor.util.AtomicFloat;
import com.matteodri.owlenergymonitor.util.MeasurementsUnmarshaller;

import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;

/**
 * Service processing messages generated by the Owl Network.
 */

@Service
public class OwlMessageProcessorImpl implements OwlMessageProcessor {

    private static final Logger logger = LogManager.getLogger(OwlMessageProcessorImpl.class);

    private MeterRegistry meterRegistry;
    private AtomicFloat currentElectricityConsumption = new AtomicFloat(0);
    private AtomicFloat todaysElectricityConsumption = new AtomicFloat(0);
    private AtomicFloat currentBatteryLevel = new AtomicFloat(0);
    private AtomicFloat currentElectricityGenerated = new AtomicFloat(0);
    private AtomicFloat currentElectricityExported = new AtomicFloat(0);
    private AtomicFloat todaysElectricityGenerated = new AtomicFloat(0);
    private AtomicFloat todaysElectricityExported = new AtomicFloat(0);

    @Autowired
    private MeasurementsUnmarshaller measurementsUnmarshaller;

    public OwlMessageProcessorImpl(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;

        setupMetrics(meterRegistry);
    }

    @Override
    public void process(InetAddress fromAddress, String message) {
        logger.debug("Message received from {}: {}", fromAddress, message);

        if (message.startsWith("<electricity")) {
            // it's an electricity measurement summary
            Electricity electricityMeasurement = measurementsUnmarshaller.unmarshalElectricityXml(message);

            if (electricityMeasurement != null && electricityMeasurement.getChannels() != null
                    && electricityMeasurement.getChannels().size() >= 1) {
                if (electricityMeasurement.getChannels().get(0).getElectricityCurrent() != null) {
                    currentElectricityConsumption
                            .set(electricityMeasurement.getChannels().get(0).getElectricityCurrent().getValue());
                }
                if (electricityMeasurement.getChannels().get(0).getElectricityDay() != null) {
                    todaysElectricityConsumption
                            .set(electricityMeasurement.getChannels().get(0).getElectricityDay().getValue());
                }
            }

            if (electricityMeasurement != null && electricityMeasurement.getBattery() != null) {
                currentBatteryLevel.set(parsePercentage(electricityMeasurement.getBattery().getLevel()));
            }

            logger.debug(
                    "Metrics set:\ncurrentElectricityConsumption={}, todaysElectricityConsumption={}, "
                            + "currentBatteryLevel={}",
                    currentElectricityConsumption, todaysElectricityConsumption, currentBatteryLevel);
        } else {
            // it's a solar measurement summary
            Solar solarMeasurement = measurementsUnmarshaller.unmarshalSolarXml(message);

            if (solarMeasurement != null && solarMeasurement.getSolarCurrent() != null) {
                if (solarMeasurement.getSolarCurrent().getGenerating() != null) {
                    currentElectricityGenerated.set(solarMeasurement.getSolarCurrent().getGenerating().getValue());
                }
                if (solarMeasurement.getSolarCurrent().getExporting() != null) {
                    currentElectricityExported.set(solarMeasurement.getSolarCurrent().getExporting().getValue());
                }

                if (solarMeasurement.getSolarDay().getGenerated() != null) {
                    todaysElectricityGenerated.set(solarMeasurement.getSolarDay().getGenerated().getValue());
                }
                if (solarMeasurement.getSolarDay().getExported() != null) {
                    todaysElectricityExported.set(solarMeasurement.getSolarDay().getExported().getValue());
                }
            }
            logger.debug(
                    "Metrics set:\ncurrentElectricityGenerated={}, currentElectricityExported={}, "
                            + "todaysElectricityGenerated={}, todaysElectricityExported={}",
                    currentElectricityGenerated, currentElectricityExported, todaysElectricityGenerated,
                    todaysElectricityExported);
        }
    }

    private void setupMetrics(MeterRegistry meterRegistry) {
        Gauge.builder("electricity_consumption_current", currentElectricityConsumption, AtomicFloat::get)
                .description("Current electricity consumption (W)").register(meterRegistry);
        Gauge.builder("electricity_consumption_today", todaysElectricityConsumption, AtomicFloat::get)
                .description("Today's electricity consumption (Wh)").register(meterRegistry);
        Gauge.builder("battery_level_current", currentBatteryLevel, AtomicFloat::get)
                .description("Current battery level (%)").register(meterRegistry);
        Gauge.builder("electricity_generated_current", currentElectricityGenerated, AtomicFloat::get)
                .description("Current electricity generation (W)").register(meterRegistry);
        Gauge.builder("electricity_exported_current", currentElectricityExported, AtomicFloat::get)
                .description("Current electricity exporting (W)").register(meterRegistry);
        Gauge.builder("electricity_generated_today", todaysElectricityGenerated, AtomicFloat::get)
                .description("Today's generated electricity (Wh)").register(meterRegistry);
        Gauge.builder("electricity_exported_today", todaysElectricityExported, AtomicFloat::get)
                .description("Today's exported electricity (Wh)").register(meterRegistry);
    }

    /**
     * Given an input string like "56%" returns the floating-point percentage value (56.0). If format is not correct it
     * will return -1. This is intentional as to make it visible when metric is changing to -1.
     *
     * @param strPercentage percentage in string format including a trailing '%' sign
     * @return floating-point representation of percentage value
     */
    private float parsePercentage(String strPercentage) {
        float returnValue = -1;
        if (strPercentage != null && !strPercentage.isEmpty() && strPercentage.endsWith("%")) {
            try {
                returnValue = Float.valueOf(strPercentage.substring(0, strPercentage.indexOf('%')));
            } catch (NumberFormatException e) {
                logger.warn("Error parsing percentage '{}'", strPercentage);
            }
        }
        return returnValue;
    }

}
