spring:
  profiles:
    active: local
  application:
    name: owl-energy-monitor

server:
  port: 7001

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

multicast-address: 224.192.32.19
multicast-port: 22600
multicast-listener-delay: 2000